### ISSUE TITLE
Update Market Creation Sub Category on Forum 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#110]
## The Chore

We need to update the Market Creation sub category on the forum to cover successor markets

## Tasks

- [ ] Update guide to creating market proposals to include successor markets including links to relevant docs and tutorials etc.
- [ ] Add successor details to the existing template for to use for proposal forum posts

## Additional details / background info

<img width="1165" alt="Screenshot 2023-06-16 at 16 50 48" src="https://github.com/vegaprotocol/ux-and-visual-design/assets/47143694/1239d1dc-6c86-47b1-85f5-b8053e1c6f68">
<img width="1165" alt="Screenshot 2023-06-16 at 16 51 31" src="https://github.com/vegaprotocol/ux-and-visual-design/assets/47143694/251b62c5-bb0e-4b32-8dd1-16923c469258">
<img width="1135" alt="Screenshot 2023-06-16 at 16 51 43" src="https://github.com/vegaprotocol/ux-and-visual-design/assets/47143694/e7417bf8-6f54-49f4-95af-8e53bd1f6e21">

**Comment by JonRay15** [comment]
Closing this as it is now covered by a task on asana which Jake is owning (and he doesnt use github)
