### ISSUE TITLE
Assign a requirements / UX lead to each feature team

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#118]
**Make sure there is a requirements / UX lead identified within each of the feature teams for deployment 2 (and 3)**
Inspired by _No UX & Design_ in _What puzzles us?_
Assigned to Jonathan Ray
Governance & Explorer Retro - 20th July 2023 retrospective
https://secure.teamretro.com/teams/5h5tYSXarX0MHQp1gMXnkg

**Comment by JonRay15** [comment]
This is done, and most of the features are now done too
