### ISSUE TITLE
Work with Gordon to make a case for moving further towards feature teams

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#119]
**Work with Gordon to make a case for moving further towards feature teams for deployment two so that they have shared success criteria etc. and propose to trial for Perps**
Inspired by _APIs _ in _What went less well?_
Assigned to Jonathan Ray
Governance & Explorer Retro - 20th July 2023 retrospective
https://secure.teamretro.com/teams/5h5tYSXarX0MHQp1gMXnkg

**Comment by JonRay15** [comment]
Also done
