### ISSUE TITLE
Make sure we do the remaining core feature spikes and lead on frontend requirements

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#121]
**Make sure we actually continue the core feature spikes even with People Make are gone 🙂 and lead more on what we need to deliver and therefore how the API needs to be presented etc.**
Inspired by _APIs _ in _What went less well?_
Assigned to Jonathan Ray
Governance & Explorer Retro - 20th July 2023 retrospective
https://secure.teamretro.com/teams/5h5tYSXarX0MHQp1gMXnkg

**Comment by JonRay15** [comment]
Have a new even better process because it is traditional in any new role to immediately assume you know best and change things
