### ISSUE TITLE
Improve panel separation

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/ux-and-visual-design#19]
The recent design updates have cleaned up the look of Console and made it visually more on-brand. However, I think the minimal design has lost some of the clarity of information architecture.

I've made some small tweaks, but one area feels like it needs a bigger change is the clarity of separation of different panels.
Looking at the below pictures, I don’t think it’s clear where one element starts and another ends, they all sort of merge into one: 

![Image](https://user-images.githubusercontent.com/1325606/192573021-791f7b90-bb78-4737-a131-2acb054c1b63.png)

This is particularly a problem on pages where the contents of the different panels is similar:

![Image](https://user-images.githubusercontent.com/1325606/192573063-9c9056f3-0c3f-4bfb-9f77-248dd10b2538.png)

In that instance, the two panels are separated by a single 1px grey horizontal line. But there are 14 other single 1px grey horizontal lines on that page, and this one doesn’t stand out any more than the others.

A couple ideas I’ve considered:

**Thicker borders**
Use 2px borders to separate panels, keep 1px borders elsewhere, and a lighter line to separate the header on the dark theme:

![Image](https://user-images.githubusercontent.com/1325606/192573153-a955f281-7bdf-4830-b366-b6949ae15ba8.png)

**Tab backgrounds**
Add a subtle background to the tab sections to break up the page:

![Image](https://user-images.githubusercontent.com/1325606/192573218-d6283a26-c1a4-43e6-96fd-a28d5cb58d77.png)

**Other options** that I’ve largely discarded:
- More spacing between panels - but we know traders don’t like wasted space
- Different border shades - which wouldn’t really work with this design where borders are shared and connected
- Disconnecting the shared borders between the primary panels, which would take up more space and wouldn’t look too good.
- Giving the panels/selected tab themselves tab a solid background to differentiate it from the other boxes, which would be a much bigger change to the design direction

This ticket is to explore/refine some of the above ideas or suggest some new ones.

**Comment by bigfandavid** [comment]
See Chore #2037 for update.

**Comment by mattrussell36** [comment]
This has been superseded by other ongoing design work

**Comment by mattrussell36** [comment]
This has been superseded by other design work
