### ISSUE TITLE
Add acceptance criteria for wallet Proof of work spam protection: `0003-WTXN` and `0001-WALL`

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/ux-and-visual-design#53]
Re: https://github.com/vegaprotocol/specs/blob/master/protocol/0072-SPPW-spam-protection-PoW.md

and https://vegaprotocol.slack.com/archives/C02KSKW6Y3F/p1664909617723239?thread_ts=1664886280.532059&cid=C02KSKW6Y3F

To reduce spam the wallet has to/may have to do some maths before submitting a transaction. This introduces a new set of errors and options that need to be handled by the wallet app and the Dapps.

- handle transaction failure due to spam protection
- handle wait time introduced by more complex math?
- add option to pre-compute things in wallet (or not) see slack thread
- give feedback on what is happening with spam protection? e.g. difficulty has increased.

**Comment by pennyandrews** [comment]
Now covered in Browser wallet A/Cs
