### ISSUE TITLE
Referrals scheme (pick up where we left off)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#64]
## Challenge

Can we increase community size through rewards  e.g. https://perp.com/referral

## Acceptance Criteria

- [ ] I can
- [ ] I can 
- [ ] I can

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

How you navigate what we legally allow people to do off chain vs on chain. People game the system and get away with it... would need to be pretty water tight.

Can we design something that we can do that achieves our goals, works with regs, and isn't gameable. Not important week one... worth considering if there is even a solution

**Comment by pennyandrews** [comment]
Closing as superseded by https://github.com/vegaprotocol/ux-and-visual-design/issues/102
