### ISSUE TITLE
Spike: IPFS deploy and its impact on the user experience

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#81]
There have been a number of mentions of IPFS deploy for console, and the potential need for a change to the user experience. 

Tasks
- [ ] Speak to Matt, Dex and Edd about what the current plan is 
- [ ] Identify what that means to what we need to do in console, on the website linking to console
- [ ] And understand what this might mean for the other front ends - is governance / token going on to IPFS for example? What else?
- [ ] Share with Barney publicly to sanity check

**Comment by campbellssource** [comment]
The job of routing to a correct version of console will not happen on the website, instead it'll link to https://console-fairground-wtf.ipns.dweb.link/ and it'll handle the rest.
Once the IPFS hosted option is working we are going to demo what we have in place and review the requirements

**Comment by mattrussell36** [comment]
This has been superseded by other work around ipfs
