### ISSUE TITLE
Alpha mainnet branding for all the channels

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#82]
There is a doc :

**Comment by bigfandavid** [comment]
Working on Stickers and Emojis with Edo and Daigan - progress can be viewed here: https://www.figma.com/file/QGqu1Yb5FD1NORc0mllKfH/Vega-Twitter%2FSocial-Assets?node-id=7536%3A76&t=UYwCiIEZsOHftSoX-1

Edo fed back yesterday, awaiting some more feedback today to get this wrapped up.

![Image](https://user-images.githubusercontent.com/113683891/212021522-452ee771-3a76-4d22-b558-8c4f66cd5f63.png)
